# Generated by Django 4.2.6 on 2023-10-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputexMain', '0002_laptop_graphics_card_laptop_is_on_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('memory', models.CharField(default='4GB GDDR6', max_length=50)),
                ('chipset', models.CharField(default='NVIDIA GeForce GTX 1650', max_length=100)),
                ('interface', models.CharField(default='PCI Express 3.0 x16', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('cores', models.PositiveIntegerField(default=4)),
                ('threads', models.PositiveIntegerField(default=8)),
                ('base_frequency', models.DecimalField(decimal_places=2, default=3.6, max_digits=4)),
                ('boost_frequency', models.DecimalField(decimal_places=2, default=4.2, max_digits=4)),
                ('socket', models.CharField(default='LGA1151', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
