# Generated by Django 4.2.6 on 2023-10-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputexMain', '0003_graphicscard_processor'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphicscard',
            name='type',
            field=models.CharField(default='graphicscard', max_length=50),
        ),
        migrations.AddField(
            model_name='laptop',
            name='type',
            field=models.CharField(default='laptop', max_length=50),
        ),
        migrations.AddField(
            model_name='monitor',
            name='type',
            field=models.CharField(default='monitor', max_length=50),
        ),
        migrations.AddField(
            model_name='processor',
            name='type',
            field=models.CharField(default='processor', max_length=50),
        ),
    ]
